can_interface = 'can0'
send_on_canbus = True
only_send_if_radio_is_in_tv_mode = False
show_label = False
toggle_fis1 = 6
toggle_fis2 = 7
lower_speed = 0
upper_speed = 100
export_speed_measurements_to_file = True
scroll_type = 'oem_style'
speed_unit = 'km/h'
temp_unit = '°C'
welcome_message_1st_line = 'WELCOME'
welcome_message_2nd_line = 'USER'
read_and_set_time_from_dashboard = True
control_pi_by_rns_e_buttons = False
read_mfsw_buttons = False
send_values_to_dashboard = True
toggle_values_by_rnse_longpress = True
initial_day_night_mode = 'night'
change_dark_mode_by_car_light = True
send_api_mediadata_to_dashboard = True
send_to_api_gauges = True
reversecamera_by_reversegear = False
reversecamera_guidelines = True
reversecamera_turn_off_delay = 5
reversecamera_turn_off_speed = 0
reversecamera_by_prev_longpress = False
reversecamera_video_pipeline = 'yuyv_30'
shutdown_via_can = 'False'
shutdown_type = 'gently'
activate_rnse_tv_input = False
tv_input_format = 'NTSC'
ENABLE_LOGGING = False
show_can_messages_in_logs = False
